# Generated by Django 2.2.7 on 2020-05-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('tamanho', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('Disponibilidade', models.BooleanField()),
            ],
        ),
    ]
