# Generated by Django 2.2.7 on 2020-05-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Medio'), ('G', 'Grande')], max_length=200),
        ),
    ]
