# Generated by Django 2.2.7 on 2020-05-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0002_auto_20200506_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itens',
            old_name='Disponibilidade',
            new_name='disponibilidade',
        ),
        migrations.AddField(
            model_name='itens',
            name='foto',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itens',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Medio'), ('G', 'Grande')], default='P', max_length=200),
        ),
    ]
