# Generated by Django 2.2.7 on 2020-05-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0003_auto_20200506_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='foto',
            field=models.ImageField(upload_to='foto'),
        ),
    ]
