# Generated by Django 2.2.7 on 2020-05-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0004_auto_20200506_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='cor',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
