# Generated by Django 2.2.7 on 2020-05-06 22:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0005_itens_cor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itens',
            new_name='Item',
        ),
        migrations.CreateModel(
            name='Fluxo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2020, 5, 6, 22, 3, 32, 771539, tzinfo=utc))),
                ('direcao', models.CharField(choices=[('E', 'Entrou'), ('S', 'Saiu')], default='S', max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizador.Item')),
            ],
        ),
    ]
