# Generated by Django 2.2.7 on 2020-06-15 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0007_auto_20200506_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rfid',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fluxo',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 18, 5, 16, 234942, tzinfo=utc)),
        ),
    ]
