# Generated by Django 2.2.7 on 2020-06-15 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0008_auto_20200615_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxo',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 18, 52, 34, 393413, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('S', 'Superior'), ('I', 'Inferior')], default='S', max_length=200),
        ),
    ]
