# Generated by Django 2.2.7 on 2020-06-15 18:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0009_auto_20200615_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxo',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 18, 59, 48, 47675, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inferior', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inferior', to='organizador.Item')),
                ('Superior', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Superior', to='organizador.Item')),
            ],
        ),
    ]
