# Generated by Django 2.2.7 on 2020-07-23 21:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0010_auto_20200615_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorito',
            old_name='Inferior',
            new_name='inferior',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='Superior',
            new_name='superior',
        ),
        migrations.AlterField(
            model_name='fluxo',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 21, 54, 25, 998365, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Escolha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferior', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inf', to='organizador.Item')),
                ('superior', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sup', to='organizador.Item')),
            ],
        ),
    ]
