# Generated by Django 2.2.7 on 2020-08-24 22:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0012_auto_20200731_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='posicao',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='fluxo',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 22, 50, 15, 655965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fluxo',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizador.Item'),
        ),
    ]
